'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
const steps=[
 {key:'who',title:'Who needs help?',options:['Me','Family member','Friend','Employee / colleague']},
 {key:'support',title:'What would you like support with?',options:['Alcohol','Substance use','Mental wellbeing','Relapse','Family challenges','Behavioural concerns','Reintegration','Other']},
 {key:'goal',title:'What are you trying to understand?',options:['Treatment options','Admission','Cost','Length of stay','Family involvement','Aftercare','Immediate support']},
];
export default function CareExplorer(){const [values,setValues]=useState({});const [index,setIndex]=useState(0);const done=index>=steps.length;const summary=useMemo(()=>`You are looking for guidance for ${values.who||'someone'} about ${values.support||'support'}, especially ${values.goal||'next steps'}.`,[values]);return <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-soft sm:p-8">{!done? <><div className="text-xs font-black uppercase tracking-[.18em] text-grace-700">Care Explorer · {index+1}/{steps.length}</div><h3 className="mt-3 text-2xl font-black">{steps[index].title}</h3><div className="mt-6 grid gap-3 sm:grid-cols-2">{steps[index].options.map(o=><button key={o} onClick={()=>{setValues(v=>({...v,[steps[index].key]:o}));setIndex(i=>i+1)}} className="rounded-2xl border border-slate-200 p-4 text-left text-sm font-bold hover:border-grace-400 hover:bg-grace-50">{o}</button>)}</div></>:<><div className="text-xs font-black uppercase tracking-[.18em] text-grace-700">Guidance, not diagnosis</div><h3 className="mt-3 text-2xl font-black">A useful next conversation</h3><p className="mt-3 leading-7 text-slate-600">{summary} These are services you may wish to discuss with our professional team. This explorer does not diagnose or determine treatment eligibility.</p><div className="mt-6 flex flex-wrap gap-3"><Link href={`/grace?topic=${encodeURIComponent(values.support||'support')}`} className="btn-primary">Ask Grace</Link><Link href="/contact" className="btn-secondary">Request confidential conversation</Link><button onClick={()=>{setValues({});setIndex(0)}} className="rounded-full px-5 py-3 text-sm font-bold text-slate-600">Start again</button></div></>}</div>}
