'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
export default function InviteStaffForm({enabled,message}){
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');const router=useRouter();
 async function submit(e){e.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');const fd=new FormData(e.currentTarget);const form=e.currentTarget;
 try{const r=await fetch('/api/admin/staff-accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName:fd.get('fullName'),email:fd.get('email'),jobTitle:fd.get('jobTitle'),department:fd.get('department'),confirm:fd.get('confirm')==='on'})});const data=await r.json();if(!r.ok)throw new Error(data.error);setNotice(data.message);form.reset();router.refresh();}catch(e){setError(e.message||'Invitation unavailable.');router.refresh();}finally{setBusy(false);}}
 return <form onSubmit={submit} className="grid gap-5"><h2 className="text-xl font-black">Invite staff member</h2>{!enabled&&<p role="status" className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{message}</p>}{[['fullName','Full name','text',120],['email','Individual email address','email',254],['jobTitle','Job title','text',120],['department','Department (optional)','text',120]].map(([name,label,type,maxLength])=><label key={name} className="grid gap-2 text-sm font-semibold">{label}<input name={name} type={type} maxLength={maxLength} required={name!=='department'} autoComplete={name==='email'?'email':name==='fullName'?'name':'off'} className="rounded-xl border border-slate-300 px-4 py-3 focus:outline-2 focus:outline-grace-700"/></label>)}<p className="text-sm leading-6 text-slate-600">New accounts receive basic staff access. Clinical cases, stock recording, approvals and other module permissions require separate authorised assignments.</p><label className="flex items-start gap-3 text-sm"><input type="checkbox" name="confirm" required className="mt-1 h-4 w-4"/>I confirm this person is authorised to join the centre’s staff portal and controls this email address.</label><button disabled={!enabled||busy} className="btn-primary disabled:opacity-50">{busy?'Creating invitation…':'Send invitation'}</button>{error&&<p role="alert" className="text-sm text-rose-800">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-grace-50 p-4 text-sm text-grace-900">{notice}</p>}</form>;
}
