import {requireSession} from '@/lib/auth';
import {listStaffAccounts} from '@/lib/staff-accounts/service';
import {ACCOUNT_ADMIN_ROLES,invitationConfiguration} from '@/lib/staff-accounts/policy.mjs';
import AppShell from '@/components/app/AppShell';
import {adminNav} from '@/lib/nav';
import InviteStaffForm from './InviteStaffForm';
export const dynamic='force-dynamic';
const labels={sending:'Sending — awaiting result',pending:'Awaiting acceptance',active:'Account activated',needs_review:'Review required',cancelled:'Cancelled'};
export default async function StaffAccounts(){await requireSession(ACCOUNT_ADMIN_ROLES);let rows=[],unavailable=false;try{rows=await listStaffAccounts();}catch{unavailable=true;}const config=invitationConfiguration(process.env);return <AppShell title="Staff Accounts" subtitle="Individual invitations and account activation" role="Administration" nav={adminNav}><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)]"><section className="rounded-3xl border border-slate-200 bg-white p-6"><InviteStaffForm enabled={config.enabled&&!unavailable} message={unavailable?'Account invitation records are unavailable. Contact the system administrator.':config.message}/></section><section className="min-w-0 rounded-3xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black">Invitation register</h2><p className="mt-2 text-sm text-slate-600">This register lists invitations created here. Existing staff accounts remain unchanged. Activated does not mean unrestricted authority or confirmed email delivery.</p><div className="mt-5 grid gap-4">{rows.map(row=><article key={row.id} className="break-words rounded-2xl border border-slate-200 p-4"><h3 className="font-bold">{row.full_name}</h3><p className="text-sm">{row.job_title}{row.department?` · ${row.department}`:''}</p><p className="mt-2 text-sm text-slate-600">{row.email}</p><p className="mt-2 text-sm font-semibold">{labels[row.status]||'Review required'}</p><p className="mt-1 text-xs text-slate-500">Created: {new Intl.DateTimeFormat('en-KE',{dateStyle:'medium',timeZone:'Africa/Nairobi'}).format(new Date(row.created_at))}</p></article>)}</div>{!rows.length&&<p className="mt-5 text-sm text-slate-500">{unavailable?'Register unavailable.':'No staff invitations have been created here yet.'}</p>}</section></div></AppShell>;}
