import Link from 'next/link';
import {requireSession} from '@/lib/auth';import {STAFF_ROLES} from '@/lib/roles';
import AppShell from '@/components/app/AppShell';
import LiveDataBanner from '@/components/app/LiveDataBanner';
import DataError from '@/components/app/DataError';
import StatusBadge from '@/components/app/StatusBadge';
import {staffNav} from '@/lib/nav';
import {graceFlowDashboard,enterpriseModules} from '@/lib/graceflow-enterprise';
import {dateTime,stageLabel} from '@/lib/format';

const staffRoles=STAFF_ROLES;
export default async function GraceFlow(){
 const s=await requireSession(staffRoles); let d,error; try{d=await graceFlowDashboard(s.token)}catch(e){error=e.message}
 return <AppShell title="GraceFlow" subtitle="Unified workflow, service and enterprise operations engine" role="GraceFlow engine" nav={staffNav}><LiveDataBanner/>{error?<DataError message={error}/>:<>
  <section className="overflow-hidden rounded-[2rem] bg-slate-950 p-7 text-white lg:p-9"><div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><div className="text-xs font-bold uppercase tracking-[.22em] text-grace-300">One operational spine</div><h2 className="mt-3 max-w-3xl text-3xl font-black tracking-tight">Every workflow enters GraceFlow, wherever the work starts.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-300">Website enquiries, portal actions, care operations and back-office work are persisted as workflow instances, events, tasks and approvals. GraceFlow coordinates people, systems and deadlines while preserving human authority for consequential decisions.</p></div><div className="grid grid-cols-2 gap-3"><K label="Active flows" value={d.activeFlows.length}/><K label="Open tasks" value={d.openTasks.length}/><K label="Pending approvals" value={d.pendingApprovals.length}/><K label="Frontend events" value={d.external.length}/></div></div></section>
  <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Link href="/staff/graceflow/designer" className="rounded-3xl border border-slate-200 bg-white p-5 hover:border-grace-300"><div className="text-xs font-black uppercase tracking-[.14em] text-grace-700">Design</div><h3 className="mt-2 font-black">Visual Workflow Designer</h3><p className="mt-2 text-sm text-slate-500">Build versioned graphs with tasks, conditions, approvals, timers and cross-module actions.</p></Link><Link href="/staff/graceflow/automation" className="rounded-3xl border border-slate-200 bg-white p-5 hover:border-grace-300"><div className="text-xs font-black uppercase tracking-[.14em] text-grace-700">Automate</div><h3 className="mt-2 font-black">Automation & Policy Centre</h3><p className="mt-2 text-sm text-slate-500">Control triggers, schedules, approval matrices, SLA targets and escalation rules.</p></Link><Link href="/staff/notifications" className="rounded-3xl border border-slate-200 bg-white p-5 hover:border-grace-300"><div className="text-xs font-black uppercase tracking-[.14em] text-grace-700">Respond</div><h3 className="mt-2 font-black">Notification Centre</h3><p className="mt-2 text-sm text-slate-500">See workflow alerts, overdue work, escalations and handoffs in one staff inbox.</p></Link><Link href="/staff/graceflow/analytics" className="rounded-3xl border border-slate-200 bg-white p-5 hover:border-grace-300"><div className="text-xs font-black uppercase tracking-[.14em] text-grace-700">Improve</div><h3 className="mt-2 font-black">Executive Process Analytics</h3><p className="mt-2 text-sm text-slate-500">Measure throughput, cycle time, automation health, bottlenecks and SLA exposure.</p></Link></section>
  <section className="mt-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">Workflow pillars</h2><p className="mt-1 text-sm text-slate-500">Intake · orchestration · approvals · execution · collaboration · records · analytics.</p></div></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{enterpriseModules.map(m=><Link href={`/staff/graceflow/${m.key}`} key={m.key} className="group rounded-3xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:border-grace-200 hover:shadow-lg"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-grace-50 px-2.5 py-1 text-[10px] font-black uppercase tracking-wide text-grace-700">{m.accent}</span><span className="text-2xl font-black text-slate-300 group-hover:text-grace-500">{d.counts[m.key]||0}</span></div><h3 className="mt-4 font-black">{m.label}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{m.description}</p><div className="mt-4 text-xs font-bold text-grace-700">Open module →</div></Link>)}</div></section>
  <div className="mt-7 grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Unified work queue</h2><p className="mt-1 text-sm text-slate-500">Tasks from care and enterprise workflows.</p></div></div><div className="mt-4 grid gap-3">{d.openTasks.slice(0,12).map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4"><div><b>{x.title}</b><div className="mt-1 text-xs text-slate-500">{stageLabel(x.task_type)} · {stageLabel(x.assigned_role||'unassigned')} · due {dateTime(x.due_at)}</div></div><StatusBadge tone={x.status==='blocked'?'warn':'neutral'}>{stageLabel(x.status)}</StatusBadge></div>)}{!d.openTasks.length&&<p className="py-6 text-sm text-slate-500">No open workflow tasks.</p>}</div></section><section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-black">Event stream</h2><p className="mt-1 text-sm text-slate-500">A traceable history of work entering and moving through GraceFlow.</p><div className="mt-4 grid gap-3">{d.events.slice(0,12).map(e=><div key={e.id} className="border-l-2 border-grace-200 pl-4"><div className="text-xs font-bold uppercase tracking-wide text-grace-700">{stageLabel(e.source_channel)} · {stageLabel(e.event_type)}</div><div className="mt-1 text-sm font-semibold">{e.summary||stageLabel(e.event_type)}</div><div className="mt-1 text-xs text-slate-400">{dateTime(e.created_at)}</div></div>)}{!d.events.length&&<p className="py-6 text-sm text-slate-500">No workflow events yet.</p>}</div></section></div>
 </>}</AppShell>
}
function K({label,value}){return <div className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="text-2xl font-black">{value}</div><div className="mt-1 text-xs text-slate-400">{label}</div></div>}
