import {createHmac} from 'node:crypto';
import {dbRpc,getAuthUser} from '@/lib/supabase-rest';
import {publicRoleAllowed} from './policy.mjs';
export async function authPublic(path,{method='POST',body}={}){
 const base=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!base||!key)throw new Error('Sign-in is not configured.');
 const r=await fetch(base+'/auth/v1'+path,{method,cache:'no-store',signal:AbortSignal.timeout(15000),headers:{apikey:key,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error('Authentication could not be completed. Check your details or try again later.');return d;
}
export async function publicProviders(){try{const s=await authPublic('/settings',{method:'GET'});return {email:Boolean(s.external?.email),signup:!s.disable_signup,google:Boolean(s.external?.google),phone:Boolean(s.external?.phone)};}catch{return {email:false,signup:false,google:false,phone:false};}}
export async function publicAuthQuota(req){const secret=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!secret)throw new Error('Sign-in is not configured.');const ip=req.headers.get('x-vercel-forwarded-for')||req.headers.get('x-real-ip')||req.headers.get('x-forwarded-for')||'unknown';const hash=createHmac('sha256',secret).update('public-auth:'+ip.split(',')[0].trim()).digest('hex');if(!await dbRpc('consume_public_auth_quota',{p_hash:hash}))throw new Error('Too many attempts. Please wait before trying again.');}
export async function publicProfile(token){const user=await getAuthUser(token);if(user.is_anonymous||(!user.email_confirmed_at&&!user.phone_confirmed_at))throw new Error('Verify your email or phone before signing in.');const profile=await dbRpc('ensure_public_account',{p_user:user.id,p_name:'Member'});if(!publicRoleAllowed(profile))throw new Error('This account cannot use public sign-in. Staff should use Staff portal.');return {user,profile};}
export function sessionCookies(res,data){res.cookies.set('lhg_access',data.access_token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:Math.min(data.expires_in||3600,3600)});if(data.refresh_token)res.cookies.set('lhg_refresh',data.refresh_token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:60*60*24*30});}
export function publicHome(role){return role==='client'?'/portal':role==='family'?'/family':'/account';}
