import {dbAdminSelect,dbInsert,dbUpdate} from '@/lib/supabase-rest';
import {sendThroughConnector} from '@/lib/connectors/router';
const waits=[0,60,300,1800,7200];
function interpolate(body,data={}){return String(body||'').replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g,(_,k)=>String(data[k]??''));}
async function template(key,channel){if(!key)return null;const rows=await dbAdminSelect('notification_templates',`template_key=eq.${encodeURIComponent(key)}&channel=eq.${encodeURIComponent(channel)}&active=eq.true&select=template_key,channel,subject,body,contains_sensitive_content&limit=1`);return rows?.[0]||null;}
export async function processNotificationOutbox({limit=20}={}){
 const now=new Date().toISOString();const rows=await dbAdminSelect('notification_outbox',`status=in.(queued,retry)&next_attempt_at=lte.${encodeURIComponent(now)}&select=*&order=created_at.asc&limit=${Math.min(50,Math.max(1,limit))}`);const summary={processed:0,sent:0,retried:0,deadLettered:0};
 for(const item of rows||[]){summary.processed++;const claimed=await dbUpdate('notification_outbox',`id=eq.${item.id}&status=in.(queued,retry)`,{status:'sending',updated_at:new Date().toISOString()});if(!claimed?.length)continue;const tpl=await template(item.template_key,item.channel);let res;if(!tpl||tpl.contains_sensitive_content){res={ok:false,retryable:false,errorCode:'template_not_permitted',errorMessage:'An approved privacy-safe template is required.'};}else{const data=item.payload||{};const text=interpolate(tpl.body,data);const subject=interpolate(tpl.subject,data);const payload=item.channel==='whatsapp'?{to:item.recipient,template:data.provider_template||item.template_key,language:data.language||'en_US',components:data.components||[]}:{to:item.recipient,text,subject};res=await sendThroughConnector(item.channel,payload);}
 const attempt=(item.attempt||0)+1;if(res.ok){await dbUpdate('notification_outbox',`id=eq.${item.id}`,{status:'sent',attempt,provider_reference:res.providerReference||null,last_error:null,updated_at:new Date().toISOString()});await dbInsert('notification_deliveries',{notification_id:item.notification_id||null,channel:item.channel,recipient:item.recipient,provider:res.provider||null,status:res.status||'accepted',provider_message_id:res.providerReference||null,attempt_count:attempt,sent_at:new Date().toISOString()});summary.sent++;}else{const dead=!res.retryable||attempt>=item.max_attempts;const delay=waits[Math.min(attempt,waits.length-1)];await dbUpdate('notification_outbox',`id=eq.${item.id}`,{status:dead?'dead_letter':'retry',attempt,last_error:res.errorCode||'delivery_failed',next_attempt_at:new Date(Date.now()+delay*1000).toISOString(),updated_at:new Date().toISOString()});await dbInsert('notification_deliveries',{notification_id:item.notification_id||null,channel:item.channel,recipient:item.recipient,provider:res.provider||null,status:dead?'dead_letter':'failed',attempt_count:attempt,last_error:res.errorCode||'delivery_failed'});dead?summary.deadLettered++:summary.retried++;}}
 return summary;
}
