import {NextResponse} from 'next/server';
import {authorised} from '@/lib/route-auth';
import {dbAdminSelect,dbInsert,dbUpdate} from '@/lib/supabase-rest';
import {createSimulation,replayRun} from '@/lib/graceflow-studio2';
const admins=['administrator','manager','super_admin'];
export async function GET(){const s=await authorised(admins);if(!s)return NextResponse.json({error:'Forbidden'},{status:403});const [forms,calendars,connectors,deadLetters,retries,replays,simulations,instances,runs,defs]=await Promise.all([
 dbAdminSelect('workflow_forms','select=*&order=updated_at.desc'),dbAdminSelect('business_calendars','select=*&order=name'),dbAdminSelect('integration_connectors','select=id,connector_key,provider_type,display_name,enabled,last_health_status,last_health_at,updated_at&order=display_name'),dbAdminSelect('workflow_dead_letters','select=*&order=created_at.desc&limit=100'),dbAdminSelect('workflow_retry_jobs','select=*&order=next_attempt_at.asc&limit=100'),dbAdminSelect('workflow_replays','select=*&order=created_at.desc&limit=50'),dbAdminSelect('workflow_simulations','select=*&order=created_at.desc&limit=50'),dbAdminSelect('workflow_instances','status=not.in.(completed,cancelled)&select=*&order=updated_at.desc&limit=300'),dbAdminSelect('workflow_engine_runs','select=*&order=started_at.desc&limit=100'),dbAdminSelect('workflow_definitions','select=id,name,module,workflow_key,status&order=name')
 ]);return NextResponse.json({forms,calendars,connectors,deadLetters,retries,replays,simulations,instances,runs,definitions:defs});}
export async function POST(req){const s=await authorised(admins);if(!s)return NextResponse.json({error:'Forbidden'},{status:403});const b=await req.json();try{
 if(b.action==='simulate')return NextResponse.json(await createSimulation({definitionId:b.definitionId,versionId:b.versionId,payload:b.payload||{},staffId:s.profile.staff_id}));
 if(b.action==='replay')return NextResponse.json(await replayRun({engineRunId:b.engineRunId,payloadOverride:b.payloadOverride||{},staffId:s.profile.staff_id}));
 if(b.action==='save_form'){const payload={workflow_definition_id:b.definitionId||null,form_key:String(b.formKey||'').trim().toLowerCase().replace(/[^a-z0-9_]+/g,'_'),name:String(b.name||'').slice(0,120),description:String(b.description||'').slice(0,500),schema:b.schema||{fields:[]},audience:b.audience||[],status:b.status||'draft'};if(!payload.form_key||!payload.name)return NextResponse.json({error:'Form name and key required'},{status:400});const rows=await dbInsert('workflow_forms',payload);return NextResponse.json({form:rows[0]});}
 if(b.action==='save_calendar'){const rows=await dbInsert('business_calendars',{name:String(b.name||'').slice(0,100),timezone:b.timezone||'Africa/Nairobi',working_days:b.workingDays||[1,2,3,4,5],work_start:b.workStart||'08:00',work_end:b.workEnd||'17:00',holidays:b.holidays||[]});return NextResponse.json({calendar:rows[0]});}
 if(b.action==='toggle_connector'){const rows=await dbUpdate('integration_connectors',`id=eq.${b.id}`,{enabled:Boolean(b.enabled),updated_at:new Date().toISOString()});return NextResponse.json({connector:rows[0]});}
 if(b.action==='resolve_dead_letter'){const rows=await dbUpdate('workflow_dead_letters',`id=eq.${b.id}`,{resolved:true,resolved_by:s.profile.staff_id||null,resolved_at:new Date().toISOString(),resolution_note:String(b.note||'Resolved from Studio').slice(0,500)});return NextResponse.json({deadLetter:rows[0]});}
 return NextResponse.json({error:'Unknown action'},{status:400});
 }catch(e){return NextResponse.json({error:e.message},{status:500})}}
