import Link from 'next/link';
import {requireSession} from '@/lib/auth';import {STAFF_ROLES} from '@/lib/roles';
import AppShell from '@/components/app/AppShell';
import {staffNav} from '@/lib/nav';
import {notificationData} from '@/lib/graceflow-control';
import {dateTime} from '@/lib/format';

const roles=STAFF_ROLES;
export default async function Page(){const s=await requireSession(roles);const rows=await notificationData(s);const unread=rows.filter(x=>!x.read_at);return <AppShell title="Notification Centre" subtitle="Workflow alerts, approvals, SLA warnings and operational handoffs" role="GraceFlow notifications" nav={staffNav}><div className="grid gap-4 md:grid-cols-3"><Card label="Unread" value={unread.length}/><Card label="Critical" value={rows.filter(x=>!x.read_at&&x.severity==='critical').length}/><Card label="All notifications" value={rows.length}/></div><section className="mt-6 rounded-3xl border border-slate-200 bg-white p-5"><div className="grid gap-3">{rows.map(n=><div key={n.id} className={`rounded-2xl border p-4 ${n.read_at?'border-slate-100 bg-slate-50':'border-grace-200 bg-white'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[.12em] text-grace-700">{n.severity} · {n.module||'workflow'}</div><h3 className="mt-1 font-black">{n.title}</h3>{n.body&&<p className="mt-1 text-sm text-slate-500">{n.body}</p>}</div><div className="text-xs text-slate-400">{dateTime(n.created_at)}</div></div><div className="mt-3 flex gap-2">{n.action_url&&<Link href={n.action_url} className="rounded-lg bg-slate-900 px-3 py-1.5 text-xs font-bold text-white">Open</Link>}{!n.read_at&&<span className="self-center text-xs font-bold text-grace-700">Unread</span>}</div></div>)}{!rows.length&&<p className="py-8 text-sm text-slate-500">No GraceFlow notifications yet.</p>}</div></section></AppShell>}
function Card({label,value}){return <div className="rounded-3xl border border-slate-200 bg-white p-5"><div className="text-3xl font-black">{value}</div><div className="mt-1 text-sm text-slate-500">{label}</div></div>}
