"use client";
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {movementColumns,parseMovementCSV,validateInventory} from '@/lib/inventory-validation.mjs';
const fieldClass='rounded-xl border border-slate-300 p-2 font-normal w-full';
const sectionClass='rounded-2xl border border-slate-200 bg-white p-5';
const date=v=>new Intl.DateTimeFormat('en-KE',{dateStyle:'medium',timeZone:'Africa/Nairobi'}).format(new Date(v));
function Field({name,label,type='text',required=true,...rest}){return <label className="grid gap-1 text-sm font-bold">{label}<input name={name} type={type} required={required} className={fieldClass} {...rest}/></label>;}
function Table({headers,rows,empty}){return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{headers.map(h=><th key={h} className="p-3 border-b">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j} className="p-3 border-b align-top">{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-4 text-slate-600">{empty}</p>}</div>;}
export default function InventoryWorkspace({data}){
 const router=useRouter();const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[csv,setCSV]=useState(null),[csvError,setCSVError]=useState('');
 const items=data.items||[],movements=data.movements||[],counts=data.counts||[];
 async function save(action,body,form){
 if(busy)return;setBusy(true);setMessage('');
 try{const response=await fetch('/api/graceflow/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,data:body})});const receipt=await response.json();if(!response.ok)throw Error(receipt.error||'Unable to confirm save.');
 const receipts=receipt.receipts||[receipt];setMessage(`${receipts.length} confirmed receipt(s): ${receipts.map(r=>r.receipt_id).join(', ')}. ${receipt.status==='pending_approval'?'Awaiting approval; stock balance is unchanged.':receipt.status==='posted'?'Stock posted.':'Saved.'}`);form?.reset();if(action==='import')setCSV(null);router.refresh();
 }catch(e){setMessage(e.message||'Unable to confirm save.');}finally{setBusy(false);}
 }
 function submit(action,event){event.preventDefault();const form=event.currentTarget,body=Object.fromEntries(new FormData(form));if(!validateInventory(action,body)){setMessage('Check the required fields and quantities.');return;}save(action,body,form);}
 const select=<label className="grid gap-1 text-sm font-bold">Item<select name="item_code" required className={fieldClass}><option value="">Select an item</option>{items.map(i=><option key={i.id} value={i.item_code}>{i.item_code} · {i.name}</option>)}</select></label>;
 const button=label=><button disabled={busy} className="rounded-xl bg-slate-950 p-3 text-sm font-bold text-white disabled:opacity-50">{busy?'Saving…':label}</button>;
 return <div className="space-y-6 mt-5">
 <p className="text-sm text-slate-600">Your assigned inventory only. Balances include posted movements. Pending submissions do not change stock. Values use each item’s configured unit cost (KES), not an accounting valuation.</p>
 <div role="status" aria-live="polite" className={message?'rounded-xl bg-grace-50 p-4 break-words':''}>{message}</div>
 <div className="grid gap-4 sm:grid-cols-3">{[['Total inventory value',`KES ${Number(data.total_value).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2})}`],['Items low in stock',data.low_stock],['Items out of stock',data.out_of_stock]].map(([label,value])=><div key={label} className={sectionClass}><h2 className="text-sm text-slate-600">{label}</h2><p className="text-2xl font-black mt-2">{value}</p></div>)}</div>
 <section className={sectionClass}><h2 className="text-xl font-bold">Inventory register</h2><p className="mt-2 text-sm">Quantity is calculated automatically. Log opening stock as an IN movement; never edit the quantity directly.</p><Table headers={['Item ID','Item name','Unit','Balance','Unit cost (KES)','Value (KES)','Reorder level','Status']} rows={items.map(i=>[i.item_code,i.name,i.unit,i.balance,i.unit_cost,(Number(i.balance)*Number(i.unit_cost)).toFixed(2),i.reorder_level,Number(i.balance)===0?'Out of stock':Number(i.balance)<=Number(i.reorder_level)?'Low stock':'In stock'])} empty="No assigned items yet."/></section>
 <section className={sectionClass}><h2 className="text-xl font-bold">Last five posted movements</h2><Table headers={['Posted','Item','In / out','Quantity','Balance after']} rows={(data.last_five||[]).map(m=>[date(m.posted_at),m.item_code,m.direction,m.quantity,m.balance_after])} empty="No movements have been posted."/></section>
 {data.can_create?<div className="grid gap-6 lg:grid-cols-2"><section className={sectionClass}><h2 className="text-xl font-bold">Add an inventory item</h2><form onSubmit={e=>submit('item',e)} className="grid gap-3 mt-4"><Field name="item_code" label="Item ID" maxLength={40} pattern="[A-Za-z0-9_-]+"/><Field name="name" label="Item name" maxLength={160}/><Field name="unit" label="Unit (for example, pieces)" maxLength={40}/><Field name="unit_cost" label="Unit cost (KES)" type="number" min="0" max="9999999999" step="0.01"/><Field name="reorder_level" label="Reorder level" type="number" min="0" max="9999999999" step="0.001"/>{button('Save item')}</form></section>
 <section className={sectionClass}><h2 className="text-xl font-bold">Log stock in / out</h2><p className="text-sm mt-2">Receipt signatures are references to signed vouchers held by the Centre. A typed name is not a signature. An independent authorised approver must verify the voucher before posting.</p><form onSubmit={e=>submit('movement',e)} className="grid gap-3 mt-4">{select}<Field name="movement_key" label="Unique movement reference" maxLength={80}/><Field name="movement_date" label="Movement date" type="date"/><label className="grid gap-1 text-sm font-bold">In / out<select name="direction" className={fieldClass}><option>IN</option><option>OUT</option></select></label><Field name="quantity" label="Quantity" type="number" min="0.001" step="0.001"/><Field name="issued_to" label="Issued to (required for OUT)" required={false} maxLength={160}/><Field name="received_from" label="Received from (required for IN)" required={false} maxLength={160}/><Field name="purpose" label="Purpose" maxLength={500}/><Field name="received_by" label="Received by" maxLength={160}/><Field name="receipt_signature" label="Signed receipt / voucher reference" maxLength={200}/>{button('Submit for approval')}</form></section></div>:<p className="text-sm">Your assignment permits reading only. Creating items, movements and counts requires a separate assignment.</p>}
 {data.can_create&&<section className={sectionClass}><h2 className="text-xl font-bold">Upload movement log</h2><p className="text-sm mt-2">Export a movement sheet as CSV using the template column names. Maximum 200 rows / 128 KB. The entire upload is validated together and remains pending approval. Keep existing references when retrying.</p><a download="LHG-movement-template.csv" href={'data:text/csv;charset=utf-8,'+encodeURIComponent(movementColumns.join(',')+'\n')} className="inline-block text-grace-700 underline my-3">Download CSV template</a><label className="block">Movement CSV<input className="block mt-2" type="file" accept=".csv,text/csv" disabled={busy} onChange={async e=>{setCSV(null);setCSVError('');try{const f=e.target.files?.[0];if(!f)return;if(f.size>128000)throw Error('CSV must be under 128 KB.');setCSV(parseMovementCSV(await f.text()));}catch(err){setCSVError(err.message);}}}/></label>{csvError&&<p role="alert">{csvError}</p>}{csv&&<><p className="my-3">{csv.length} valid rows ready. Review item IDs and references before saving.</p><Table headers={['Reference','Item','Direction','Quantity']} rows={csv.slice(0,5).map(m=>[m.movement_key,m.item_code,m.direction,m.quantity])}/><button disabled={busy} onClick={()=>save('import',csv)} className="bg-slate-950 text-white rounded-xl p-3">Submit {csv.length} movements for approval</button></>}</section>}
 <section className={sectionClass}><h2 className="text-xl font-bold">Movement log and approval queue</h2><p className="text-sm mt-2">Latest 200 submissions. Approved by is the trusted account ID; signature references link to retained signed vouchers.</p><Table headers={['Date','Reference','Item','In / out','Qty','Issued to / received from','Purpose','Received by','Receipt signature','Approved by / signature','Balance after','Action']} rows={movements.map(m=>[date(m.movement_date),m.movement_key,m.item_code,m.direction,m.quantity,m.direction==='OUT'?m.issued_to:m.received_from,m.purpose,m.received_by,m.receipt_signature,m.approved_by?`${m.approved_by} / ${m.approval_signature}`:'Pending',m.balance_after??'Not posted',m.posted_at?'Posted':items.find(i=>i.id===m.item_id)?.can_post?<form onSubmit={e=>submit('post',e)} className="grid gap-2 min-w-48"><input type="hidden" name="item_code" value={m.item_code}/><input type="hidden" name="movement_id" value={m.id}/><Field name="approval_signature" label="Verified signed approval voucher reference" maxLength={200}/>{button('Approve and post')}</form>:'Assigned independent approver required'])} empty="No movements yet."/></section>
 <section className={sectionClass}><h2 className="text-xl font-bold">Friday physical count review</h2><p className="text-sm mt-2">Every Friday, count each item and compare with the register. Saving captures the current posted balance and variance. It never changes stock; resolve differences through reviewed IN / OUT movements. For another day, explain why in the reason.</p>{data.can_create&&<form onSubmit={e=>submit('count',e)} className="grid gap-3 mt-4 sm:grid-cols-2">{select}<Field name="count_key" label="Unique count reference" maxLength={80}/><Field name="counted_quantity" label="Physical quantity" type="number" min="0" step="0.001"/><Field name="reason" label="Count notes / off-Friday reason" maxLength={500}/>{button('Save count snapshot')}</form>}<Table headers={['Recorded (Nairobi)','Item','System qty','Physical qty','Variance','Notes']} rows={counts.map(c=>[date(c.created_at),c.item_code,c.system_quantity,c.counted_quantity,c.variance,c.reason])} empty="No count reviews yet."/></section>
 <details className={sectionClass}><summary className="font-bold cursor-pointer">Staff SOP and formulas</summary><ol className="list-decimal pl-5 space-y-2 mt-3"><li>Create an item with its ID, name, unit, unit cost and reorder level. Opening stock is an IN movement.</li><li>Record every receipt or issue with a unique reference, date, quantity and purpose. OUT requires issued to, received by and a signed receipt voucher.</li><li>An independent user with assigned read, approve and execute authority verifies the signed approval voucher and posts the movement. Self-approval and negative stock are blocked.</li><li>Never edit quantity directly. Balance = posted IN − posted OUT. Item value = balance × unit cost. Total value = sum of assigned item values.</li><li>Low stock = positive balance at or below reorder level. Out of stock = zero balance. Pending movements are excluded.</li><li>Every Friday, count all assigned items. Variance = physical count − recorded system balance. Retain signed vouchers and investigate differences before submitting correction movements.</li><li>CSV imports are atomic and use the same checks. Reuse references and original details when retrying; conflicting duplicates are rejected. Do not upload client or medical information.</li></ol></details>
 </div>;
}
