import Link from 'next/link';
import { HeartIcon, ShieldCheckIcon, UserGroupIcon, SparklesIcon, HomeModernIcon, ArrowRightIcon, CheckCircleIcon } from '@heroicons/react/24/outline';
import CTA from '@/components/CTA';
import TrustStrip from '@/components/TrustStrip';
import FAQ from '@/components/FAQ';

const programs=[['Substance Use Recovery','Structured rehabilitation support focused on recovery skills, routines, accountability and relapse prevention.'],['Mental & Emotional Wellbeing','Supportive care pathways designed around individual assessment, counselling and healthy coping strategies.'],['Family Support','Guidance and education for families so recovery can continue within a healthier, more informed support system.']];
const principles=[[HeartIcon,'Compassion first'],[ShieldCheckIcon,'Privacy & dignity'],[UserGroupIcon,'Family-inclusive care'],[SparklesIcon,'Recovery with purpose']];
const journey=['Private enquiry','Initial screening','Professional assessment','Individual recovery plan','Progress review','Transition & aftercare'];

export default function Home(){return <>
<section className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 opacity-30 [background:radial-gradient(circle_at_70%_20%,#4a9e86_0,transparent_35%),radial-gradient(circle_at_20%_80%,#bf9640_0,transparent_25%)]"/><div className="container-page relative grid min-h-[690px] items-center gap-12 py-20 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-grace-300">Rehabilitation • Treatment • Restoration</p><h1 className="mt-6 max-w-4xl text-5xl font-black leading-[1.03] tracking-tight sm:text-6xl lg:text-7xl">Recovery begins with one conversation.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Compassionate, structured and confidential rehabilitation support for individuals and families seeking stability, recovery and a healthier path forward.</p><div className="mt-9 flex flex-wrap gap-4"><Link className="rounded-full bg-grace-500 px-7 py-3.5 font-semibold text-white transition hover:bg-grace-400" href="/grace">Talk to Grace</Link><Link className="rounded-full border border-white/20 px-7 py-3.5 font-semibold transition hover:bg-white/10" href="/contact">Request Confidential Assessment</Link></div><p className="mt-6 text-sm text-slate-400">For urgent medical or psychiatric emergencies, contact emergency services or go to the nearest hospital.</p></div><div className="rounded-[2rem] border border-white/10 bg-white/5 p-8 backdrop-blur"><p className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-grace-300">What you can expect</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2">{principles.map(([Icon,t])=><div key={t} className="rounded-3xl bg-white/[.07] p-5"><Icon className="h-8 w-8 text-grace-300"/><div className="mt-4 font-bold">{t}</div></div>)}</div></div></div></section>
<TrustStrip/>
<section className="section bg-gradient-to-b from-violet-50 to-white"><div className="container-page grid items-center gap-10 lg:grid-cols-[1fr_.8fr]"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-violet-700">Grace Intelligence Platform</p><h2 className="h2">An intelligent front door to care — with clear boundaries.</h2><p className="lead">Grace helps patients, families and visitors understand services, navigate admissions, find approved recovery information and connect with the right human team. Grace does not diagnose, prescribe or replace qualified professionals.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/grace" className="rounded-full bg-violet-600 px-6 py-3 text-sm font-bold text-white hover:bg-violet-700">Talk to Grace</Link><Link href="/admissions" className="btn-secondary">Explore admissions</Link></div></div><div className="rounded-[2rem] border border-violet-100 bg-white p-7 shadow-soft"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-100"><SparklesIcon className="h-6 w-6 text-violet-700"/></span><div><div className="font-black">Grace — Guidance with dignity.</div><div className="text-sm text-slate-500">Support with boundaries.</div></div></div><div className="mt-6 grid gap-3 text-sm text-slate-600">{['Approved Centre knowledge','Admissions & service navigation','Family guidance','Human handoff when judgement is needed'].map(x=><div key={x} className="flex items-center gap-3 rounded-2xl bg-violet-50/60 p-3"><CheckCircleIcon className="h-5 w-5 text-violet-600"/>{x}</div>)}</div></div></div></section>
<section className="section"><div className="container-page"><p className="eyebrow">Our approach</p><h2 className="h2">Treatment centred on the whole person.</h2><p className="lead">Recovery is not only about stopping a harmful pattern. It is about rebuilding stability, relationships, confidence, routines and hope.</p><div className="mt-10 grid gap-6 md:grid-cols-3">{programs.map(([t,d])=><article className="card" key={t}><div className="mb-5 grid h-12 w-12 place-items-center rounded-2xl bg-grace-100"><HomeModernIcon className="h-6 w-6 text-grace-800"/></div><h3 className="text-xl font-bold text-slate-950">{t}</h3><p className="mt-3 leading-7 text-slate-600">{d}</p><Link className="mt-6 inline-flex items-center gap-2 font-semibold text-grace-800" href="/programs">Learn more <ArrowRightIcon className="h-4 w-4"/></Link></article>)}</div></div></section>
<section className="section bg-grace-50"><div className="container-page grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Recovery pathway</p><h2 className="h2">Know what happens next.</h2><p className="lead">Families often reach out during an uncertain period. A visible care pathway makes the first steps easier to understand and reduces unnecessary anxiety.</p><Link href="/admissions" className="btn-secondary mt-7">View admissions guide</Link></div><div className="grid gap-3">{journey.map((x,i)=><div key={x} className="flex items-center gap-4 rounded-2xl bg-white p-5 shadow-sm"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-grace-800 font-bold text-white">{i+1}</span><p className="font-semibold text-slate-800">{x}</p><CheckCircleIcon className="ml-auto h-5 w-5 text-grace-600"/></div>)}</div></div></section>
<section className="section"><div className="container-page grid gap-8 lg:grid-cols-3"><div className="lg:col-span-1"><p className="eyebrow">Support beyond the individual</p><h2 className="h2">Recovery works better with informed support.</h2></div><div className="card lg:col-span-2"><div className="grid gap-8 md:grid-cols-2"><div><h3 className="text-xl font-bold">For individuals</h3><p className="mt-3 leading-7 text-slate-600">Understand the admission process, program expectations, privacy, routines and transition planning before committing to the next step.</p></div><div><h3 className="text-xl font-bold">For families</h3><p className="mt-3 leading-7 text-slate-600">Learn how to support recovery, establish healthy boundaries, participate appropriately and prepare for reintegration after structured care.</p></div></div></div></div></section>
<FAQ/>
<CTA />
</>}
