export const PROGRAMS={
'assessment-admissions':{title:'Assessment & Admissions',intro:'A clear, confidential starting point when you are unsure where to begin.',sections:[
['Who this may be for','People seeking help for themselves, families or caregivers seeking guidance, and people referred for an initial conversation or assessment.'],
['What the pathway may include','A confidential initial enquiry, initial screening, assessment, understanding the person’s circumstances and needs, identifying an appropriate care pathway, admission preparation, arrival and orientation, and referral to appropriate external care where the Centre cannot safely meet a person’s needs.'],
['How care is individualized','The website does not determine a clinical level of care. Appropriate next steps depend on professional assessment and individual circumstances.'],
['Family and caregiver questions','Families and caregivers can ask about the admissions process and how they can support the person. Protected information remains governed by consent, authorized relationships, confidentiality requirements and Centre policy.'],
['Before admission','The team can explain confirmed preparation requirements, what to expect, and what to bring once Centre policy has been verified. Fees or payment information should only be published when confirmed.']]},
'residential-rehabilitation':{title:'Residential Rehabilitation',intro:'A structured residential environment supporting an individualized recovery journey following assessment.',sections:[
['What support may include','Assessment and individualized care planning, daily routines, individual counselling and group support where offered, recovery education, peer support, life-skills development, wellness or recreation where applicable, and progress reviews.'],
['Family involvement','Family involvement may form part of care where appropriate and consented. Participation does not override confidentiality.'],
['Typical care journey','Assessment → individualized planning → structured recovery support → progress review → relapse-prevention and discharge preparation → reintegration planning → transition into aftercare.']]},
'outpatient-support':{title:'Outpatient Support',intro:'Scheduled recovery support for people whose assessed circumstances are appropriate for care while living at home.',sections:[
['How it differs from residential care','Outpatient care can allow suitable clients to maintain appropriate work, school or family responsibilities while attending scheduled counselling or support sessions.'],
['What support may include','Recovery monitoring, individual or group support where offered, relapse-prevention work, recovery goals, consented family involvement, periodic reassessment and transition to longer-term community or aftercare support.'],
['Suitability','Outpatient suitability is determined through assessment and individual circumstances rather than website self-selection. Additional care or referral may be recommended when needs change.']]},
'relapse-prevention':{title:'Relapse Prevention',intro:'An ongoing recovery capability focused on awareness, preparation and timely support.',sections:[
['What this may address','Personal triggers, early warning signs, coping and craving-management strategies, high-risk situations, emotional regulation, healthy routines and support networks.'],
['Personal recovery planning','Support can include personal recovery planning, recovery-plan reviews, appropriate peer or community resources, and preparing what to do when someone feels at risk.'],
['Following a lapse','A lapse should prompt a constructive response and review of support needs rather than shame. Clients can request additional support when difficulties emerge.'],
['Connected recovery journey','For authenticated clients, approved information may connect safely with My Journey, Recovery Passport and Ask for Support. Raw clinical notes are never exposed through this public page.']]},
'family-program':{title:'Family Program',intro:'Support for families and caregivers while protecting the dignity, privacy and autonomy of the client.',sections:[
['What support may include','Family education, understanding addiction and recovery, communication, healthy boundaries, rebuilding trust, supporting recovery without enabling harmful behaviour, and family or caregiver wellbeing.'],
['Working together','Where appropriate, support may include family meetings or counselling, preparation for discharge and reintegration, longer-term recovery support and family resources.'],
['Confidentiality','Family participation does not automatically provide access to a client’s treatment information. Information sharing is governed by the client’s consent, authorized relationships, confidentiality requirements and Centre policy.']]},
'life-skills-reintegration':{title:'Life Skills & Reintegration',intro:'Practical preparation for a stable, purposeful life beyond structured treatment.',sections:[
['Building everyday capability','Where genuinely offered, support may address independent living skills, routines, responsibility, self-management, goal setting, communication, healthy relationships and conflict management.'],
['Opportunity and stability','Support may include basic financial capability, employment readiness, CV and interview preparation, education or training pathways, digital skills, community participation and housing or stability planning where appropriate.'],
['One recovery record','Approved reintegration goals may eventually appear in My Journey, Recovery Passport and the Reintegration Plan for authenticated clients. These experiences must use authoritative records rather than duplicate sources of truth.']]},
'mental-health-wellbeing':{title:'Mental Health & Wellbeing Support',intro:'Emotional and psychological wellbeing support within the Centre’s verified scope, coordinated with the wider recovery journey.',sections:[
['What support may include','Emotional wellbeing support, counselling where appropriately provided, stress and anxiety support, emotional regulation, and trauma-informed approaches only where appropriately qualified.'],
['When additional care is needed','Needs requiring additional professional assessment should be identified and referred to appropriate medical, psychiatric or specialist services.'],
['Professional boundaries','This page does not claim psychiatric diagnosis, medical treatment, trauma therapy or other regulated services unless those services and professional credentials are verified. Grace does not diagnose mental-health conditions.']]},
'aftercare':{title:'Aftercare',intro:'Recovery continues after a structured program. Aftercare supports continuity, connection and early response when needs change.',sections:[
['What support may include','Individualized aftercare planning, scheduled follow-ups, recovery check-ins, counselling or support where appropriate, relapse-prevention review, recovery goals and peer or community recovery connections.'],
['Life beyond treatment','Follow-up may include consented family involvement, employment, education and reintegration support, early identification of emerging difficulties and longer-term recovery planning.'],
['A continuous journey','Recovery Passport, My Journey, Ask for Support / My Requests and GraceFlow should support one continuous recovery journey rather than disconnected modules. Re-entry or referral pathways can be considered when needs change.']]}
};