'use client';
import {useMemo,useState} from 'react';

const TYPES=[['task','Human task'],['condition','Condition'],['approval','Approval'],['notification','Notification'],['delay','Delay / timer'],['create_record','Create module record'],['connector','Connector action'],['subflow','Reusable subflow'],['form','Form request']];
const ROLES=['counsellor','clinician','admissions','finance','administrator','manager','super_admin','hr','procurement','inventory','project_manager','helpdesk','marketing','accountant','field_service'];
const MODULES=['care','purchase','inventory','hr','helpdesk','timesheets','project','crm','sign','accounting','discuss','documents','field-service','email-marketing'];
export default function WorkflowBuilder({definition,initialVersion}){
 const seed=initialVersion?.graph||{nodes:[{id:'start',type:'start',title:'Start',position:{x:80,y:120}},{id:'end',type:'end',title:'Complete',position:{x:680,y:120}}],edges:[{id:'e1',from:'start',to:'end'}]};
 const [nodes,setNodes]=useState((seed.nodes||[]).map((n,i)=>({...n,position:n.position||{x:80+i*220,y:120}})));const [selected,setSelected]=useState(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [latestVersion,setLatestVersion]=useState(initialVersion);const [payload,setPayload]=useState('{\n  "amount": 0,\n  "priority": "routine"\n}');const [trace,setTrace]=useState([]);
 const graph=useMemo(()=>({nodes,edges:buildEdges(nodes)}),[nodes]);
 function add(type){const id=`${type}_${Date.now().toString(36)}`;const idx=nodes.filter(n=>!['start','end'].includes(n.type)).length;const node={id,type,title:TYPES.find(x=>x[0]===type)?.[1]||type,position:{x:280+(idx%3)*240,y:80+Math.floor(idx/3)*150},config:defaultConfig(type)};setNodes(ns=>[...ns.filter(n=>n.type!=='end'),node,...ns.filter(n=>n.type==='end')]);setSelected(id)}
 function update(id,patch){setNodes(ns=>ns.map(n=>n.id===id?{...n,...patch}:n))} function config(id,key,value){setNodes(ns=>ns.map(n=>n.id===id?{...n,config:{...(n.config||{}),[key]:value}}:n))} function remove(id){setNodes(ns=>ns.filter(n=>n.id!==id));setSelected(null)}
 function drop(e){e.preventDefault();const id=e.dataTransfer.getData('nodeId');if(!id)return;const r=e.currentTarget.getBoundingClientRect();update(id,{position:{x:Math.max(10,e.clientX-r.left-80),y:Math.max(10,e.clientY-r.top-30)}})}
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/graceflow/designer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save_version',definitionId:definition.id,graph,changeNote:'Saved from GraceFlow Studio 2.0'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Save failed');setLatestVersion(d.version);setMessage(`Draft v${d.version.version} saved.`)}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function publish(){if(!latestVersion?.id)return;setBusy(true);try{const r=await fetch('/api/graceflow/designer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'publish_version',versionId:latestVersion.id})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Publish failed');setLatestVersion(v=>({...v,status:'published'}));setMessage(`Version ${latestVersion.version} published.`)}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function simulate(){setBusy(true);setMessage('');try{let p={};try{p=JSON.parse(payload)}catch{throw new Error('Test payload must be valid JSON')}let version=latestVersion;if(!version?.id){await save();throw new Error('Draft saved. Run simulation again.')}const r=await fetch('/api/graceflow/studio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'simulate',definitionId:definition.id,versionId:version.id,payload:p})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Simulation failed');setTrace(d.trace||[]);setMessage(`Dry run completed: ${d.steps} simulated steps. No production records were changed.`)}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 const active=nodes.find(n=>n.id===selected);
 return <div className="grid gap-6 2xl:grid-cols-[1fr_360px]">
  <section className="rounded-3xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-black uppercase tracking-[.18em] text-grace-700">GraceFlow Studio 2.0</div><h2 className="mt-1 text-xl font-black">Drag-and-drop workflow canvas</h2><p className="mt-1 text-sm text-slate-500">Design safely in draft, test with dry-run payloads, then publish deliberately.</p></div><div className="flex flex-wrap gap-2"><button onClick={simulate} disabled={busy} className="rounded-xl border px-4 py-2 text-xs font-bold">Simulate</button><button onClick={save} disabled={busy} className="rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white">Save draft</button><button onClick={publish} disabled={busy||!latestVersion?.id} className="rounded-xl bg-grace-600 px-4 py-2 text-xs font-bold text-white">Publish v{latestVersion?.version||'—'}</button></div></div>
  <div className="mt-4 flex flex-wrap gap-2">{TYPES.map(([t,l])=><button key={t} onClick={()=>add(t)} className="rounded-full bg-slate-100 px-3 py-2 text-xs font-bold hover:bg-grace-50">+ {l}</button>)}</div>{message&&<div className="mt-4 rounded-xl bg-grace-50 px-4 py-3 text-sm font-semibold text-grace-900">{message}</div>}
  <div onDragOver={e=>e.preventDefault()} onDrop={drop} className="relative mt-5 h-[650px] overflow-auto rounded-2xl border border-dashed border-slate-300 bg-slate-50 [background-image:radial-gradient(#cbd5e1_1px,transparent_1px)] [background-size:20px_20px]">
   {nodes.map(n=><button draggable onDragStart={e=>e.dataTransfer.setData('nodeId',n.id)} onClick={()=>setSelected(n.id)} key={n.id} style={{left:n.position?.x||40,top:n.position?.y||40}} className={`absolute w-44 cursor-move rounded-2xl border bg-white p-4 text-left shadow-sm ${selected===n.id?'border-grace-500 ring-2 ring-grace-100':'border-slate-200'}`}><div className="text-[10px] font-black uppercase tracking-wider text-grace-700">{n.type}</div><div className="mt-1 text-sm font-black">{n.title}</div><div className="mt-2 text-[11px] text-slate-400">Drag to position</div></button>)}
  </div>
  {trace.length>0&&<div className="mt-5 rounded-2xl border border-slate-200 p-4"><h3 className="font-black">Simulation trace</h3><div className="mt-3 grid gap-2">{trace.map((x,i)=><div key={i} className="rounded-xl bg-slate-50 px-3 py-2 text-xs"><b>{i+1}. {x.title||x.nodeId||x.status}</b><span className="ml-2 text-slate-500">{x.type||''} · {x.status}</span>{x.detail&&<pre className="mt-2 overflow-auto whitespace-pre-wrap text-[11px] text-slate-500">{JSON.stringify(x.detail,null,2)}</pre>}</div>)}</div></div>}
  </section>
  <aside className="space-y-5"><section className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="font-black">Test payload</h3><p className="mt-1 text-xs text-slate-500">Dry runs never execute connector actions or mutate production records.</p><textarea value={payload} onChange={e=>setPayload(e.target.value)} rows={10} className="mt-3 w-full rounded-2xl border border-slate-200 p-3 font-mono text-xs"/></section>{active&&<Inspector node={active} update={update} config={config} remove={remove}/>}</aside>
 </div>
}
function Inspector({node,update,config,remove}){const c=node.config||{};return <section className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="font-black">Node inspector</h3><label className="mt-4 grid gap-1 text-xs font-bold">Title<input value={node.title||''} onChange={e=>update(node.id,{title:e.target.value})} className="rounded-xl border p-2 text-sm font-normal"/></label>{node.type==='task'&&<><Select label="Assigned role" value={c.assignedRole||''} onChange={v=>config(node.id,'assignedRole',v)} options={ROLES}/><Field label="Due in minutes" value={c.dueMinutes||''} onChange={v=>config(node.id,'dueMinutes',v)}/></>}{node.type==='delay'&&<Field label="Delay minutes" value={c.minutes||60} onChange={v=>config(node.id,'minutes',v)}/>} {node.type==='create_record'&&<><Select label="Module" value={c.module||'care'} onChange={v=>config(node.id,'module',v)} options={MODULES}/><Field label="Record type" value={c.recordType||''} onChange={v=>config(node.id,'recordType',v)}/></>}{node.type==='connector'&&<><Select label="Connector" value={c.connector||'email'} onChange={v=>config(node.id,'connector',v)} options={['email','sms','whatsapp']}/><Field label="Action" value={c.action||'send'} onChange={v=>config(node.id,'action',v)}/></>}{node.type==='subflow'&&<Field label="Workflow definition ID" value={c.workflowDefinitionId||''} onChange={v=>config(node.id,'workflowDefinitionId',v)}/>} {node.type==='form'&&<Field label="Form key" value={c.formKey||''} onChange={v=>config(node.id,'formKey',v)}/>} {node.type==='notification'&&<><Select label="Channel" value={c.channel||'in_app'} onChange={v=>config(node.id,'channel',v)} options={['in_app','email','sms','whatsapp']}/><Field label="Message" value={c.body||''} onChange={v=>config(node.id,'body',v)}/></>}{node.type==='approval'&&<Select label="Approver role" value={c.approverRole||'manager'} onChange={v=>config(node.id,'approverRole',v)} options={ROLES}/>} {!['start','end'].includes(node.type)&&<button onClick={()=>remove(node.id)} className="mt-5 text-xs font-bold text-red-600">Remove node</button>}</section>}
function Field({label,value,onChange}){return <label className="mt-3 grid gap-1 text-xs font-bold">{label}<input value={value} onChange={e=>onChange(e.target.value)} className="rounded-xl border p-2 text-sm font-normal"/></label>}function Select({label,value,onChange,options}){return <label className="mt-3 grid gap-1 text-xs font-bold">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="rounded-xl border p-2 text-sm font-normal">{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function defaultConfig(type){if(type==='task')return{assignedRole:'staff',dueMinutes:240};if(type==='delay')return{minutes:60};if(type==='approval')return{approverRole:'manager',minApprovals:1};if(type==='notification')return{channel:'in_app',body:''};if(type==='create_record')return{module:'care',recordType:'workflow_record'};if(type==='connector')return{connector:'email',action:'send'};return{}}
function buildEdges(nodes){const ordered=nodes.slice();return ordered.slice(0,-1).map((n,i)=>({id:`e-${n.id}-${ordered[i+1].id}`,from:n.id,to:ordered[i+1].id}))}
