import Link from 'next/link';
import { HomeIcon, UsersIcon, CalendarDaysIcon, DocumentTextIcon, BanknotesIcon, ChartBarIcon, ArrowPathRoundedSquareIcon, ClipboardDocumentCheckIcon, ShieldCheckIcon, SparklesIcon, Squares2X2Icon } from '@heroicons/react/24/outline';

const icons={home:HomeIcon,admissions:ClipboardDocumentCheckIcon,cases:UsersIcon,schedule:CalendarDaysIcon,documents:DocumentTextIcon,billing:BanknotesIcon,analytics:ChartBarIcon,flow:ArrowPathRoundedSquareIcon,security:ShieldCheckIcon,grace:SparklesIcon,modules:Squares2X2Icon};
export default function AppShell({children,title,subtitle,role='Staff',nav=[]}){
 return <div className="min-h-screen bg-slate-100 text-slate-900"><div className="flex min-h-screen">
  <aside className="hidden w-72 shrink-0 border-r border-slate-200 bg-slate-950 text-white xl:block"><div className="p-7"><Link href="/staff" className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-grace-500 font-black">LG</span><span><b className="block text-sm">Loving Hand of Grace</b><span className="text-xs text-slate-400">Staff Portal</span></span></Link></div><div className="px-4"><div className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[.2em] text-slate-500">{role}</div>{nav.map(x=>{const I=icons[x.icon]||HomeIcon;return <Link key={x.href} href={x.href} className="mb-1 flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-slate-300 hover:bg-white/10 hover:text-white"><I className="h-5 w-5"/>{x.label}</Link>})}</div><div className="fixed bottom-0 w-72 border-t border-white/10 bg-slate-950 p-5 text-xs leading-5 text-slate-500">GraceFlow records and coordinates work. Consequential clinical, safeguarding, HR and financial decisions remain with authorised staff.</div></aside>
  <main className="min-w-0 flex-1"><header className="border-b border-slate-200 bg-white"><div className="px-5 py-5 sm:px-8 lg:px-10"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-grace-700">Staff Portal</div><h1 className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div><div className="flex items-center gap-3"><Link href="/staff/graceflow" className="rounded-full bg-slate-950 px-4 py-2 text-xs font-bold text-white">Open GraceFlow</Link><span className="rounded-full bg-grace-50 px-3 py-1.5 text-xs font-bold text-grace-800">Secure workspace</span><form action="/api/auth/logout" method="post"><button className="rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold hover:bg-slate-50">Sign out</button></form></div></div><nav className="mt-5 flex gap-2 overflow-x-auto pb-1 xl:hidden">{nav.map(x=><Link key={x.href} href={x.href} className="whitespace-nowrap rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700">{x.label}</Link>)}</nav></div></header><div className="p-5 sm:p-8 lg:p-10">{children}</div>
  </main></div></div>
}
