import Link from 'next/link';
import {notFound} from 'next/navigation';
import ServiceAccordion from '@/components/ServiceAccordion';
import { centre } from '@/lib/config';
import {serviceSlugs,getService} from '@/lib/services';

export function generateStaticParams(){return serviceSlugs.map(slug=>({slug}))}
export function generateMetadata({params}){const s=getService(params.slug);return s?{title:`${s.title} | Loving Hand of Grace`,description:s.shortDescription}:{title:'Service not found'} }
function Anchor({children,href='/contact',secondary=false}){return <Link href={href} className={secondary?'btn-secondary':'btn-primary'}>{children}</Link>}
export default function ServiceDetail({params}){
 const s=getService(params.slug); if(!s)notFound();
 return <><section className="bg-gradient-to-b from-grace-50 to-white py-10 sm:py-14"><div className="container-page"><nav aria-label="Breadcrumb" className="mb-8 text-sm text-slate-500"><Link href="/">Home</Link><span className="mx-2">/</span><Link href="/services">Services</Link><span className="mx-2">/</span><span aria-current="page" className="text-slate-800">{s.title}</span></nav><p className="eyebrow">{s.type}</p><h1 className="mt-4 max-w-4xl text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">{s.title}</h1><p className="lead">{s.heroDescription}</p><p className="mt-4 text-sm text-slate-600">Enquiries are handled confidentially. Please do not include medical details in a public enquiry.</p><div className="mt-8 flex flex-wrap gap-3"><Anchor>Request Confidential Support</Anchor><Anchor href="/contact" secondary>Contact the Centre</Anchor></div></div></section>
 <section className="section"><div className="container-page grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Who this is for</p><h2 className="h2">Support shaped around the person.</h2></div><div className="card"><p className="text-lg leading-8 text-slate-700">{s.audience}</p><p className="mt-5 text-sm leading-7 text-slate-600">Typical needs, participation arrangements and service suitability are discussed privately. Final suitability is determined through a confidential assessment and appropriate professional review.</p></div></div></section>
 <section className="section bg-slate-50"><div className="container-page"><p className="eyebrow">What it includes</p><h2 className="h2">A coordinated support plan</h2><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{s.includes.map((x,i)=><article className="card" key={x}><span className="grid h-10 w-10 place-items-center rounded-xl bg-grace-100 font-black text-grace-800">{i+1}</span><h3 className="mt-5 text-lg font-bold">{x}</h3><p className="mt-2 text-sm leading-6 text-slate-600">Discussed and tailored according to assessment, consent and the person’s goals.</p></article>)}</div></div></section>
 <section className="section"><div className="container-page"><p className="eyebrow">How it works</p><h2 className="h2">Five clear steps</h2><ServiceAccordion items={s.processSteps.map(([title, body], index) => [`${index + 1}. ${title}`, body])}/></div></section>
 <section className="section bg-grace-50"><div className="container-page grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">Expected outcomes</p><h2 className="h2">Practical progress, reviewed with care.</h2><p className="mt-4 leading-7 text-slate-600">Outcomes vary by person and are never guaranteed. The team reviews progress with the participant and adjusts support or referrals where appropriate.</p></div><ul className="grid gap-3">{s.outcomes.map(x=><li key={x} className="rounded-2xl border border-grace-100 bg-white p-4 text-sm font-semibold text-slate-700">{x}</li>)}</ul></div></section>
 <section className="section"><div className="container-page grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">Practical information</p><h2 className="h2">What to expect</h2></div><div className="grid gap-4">{s.practicalInformation.map(([title,body])=><div key={title} className="rounded-2xl border border-slate-200 p-5"><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></div>)}</div></div></section>
 <section className="section bg-slate-50"><div className="container-page max-w-4xl"><p className="eyebrow">Frequently asked questions</p><h2 className="h2">Questions people often ask</h2><ServiceAccordion items={s.faqs}/></div></section>
 <section className="section"><div className="container-page"><h2 className="h2">Related services</h2><div className="mt-6 grid gap-4 sm:grid-cols-3">{s.relatedServices.map(slug => <Link key={slug} href={`/services/${slug}`} className="card font-bold text-grace-800 hover:bg-grace-50 active:bg-grace-100">{getService(slug)?.title || "Explore services"}</Link>)}</div></div></section><section className="section"><div className="container-page rounded-[2rem] bg-slate-950 px-7 py-10 text-white sm:px-10"><p className="text-xs font-black uppercase tracking-[.2em] text-grace-300">Ready to talk?</p><h2 className="mt-3 text-3xl font-black">Take the next step confidentially.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-300">Request support or book an assessment through the Centre’s confidential enquiry pathway. Urgent medical or psychiatric concerns require emergency services or the nearest hospital.</p><div className="mt-7 flex flex-wrap gap-3"><Anchor>Request Confidential Support</Anchor><Anchor href="/contact" secondary>Book an Assessment</Anchor><a className="btn-secondary" href={"tel:" + centre.phone.replace(/[^+0-9]/g, "")}>Speak to the Centre</a></div><address className="mt-6 space-y-2 not-italic text-slate-200"><p>{centre.phone}</p><a className="underline" href={"mailto:" + centre.email}>{centre.email}</a><p>{centre.address}</p></address></div></section></>
}
