import Link from 'next/link'; import PageHero from '@/components/PageHero';
export const metadata={title:'Programs & Care Pathways'};
const programs=[
['assessment-admissions','Assessment & Admissions','A confidential starting point to understand your circumstances, questions and the next appropriate step.','Start here'],
['residential-rehabilitation','Residential Rehabilitation','A structured residential environment supporting an individualized recovery journey following assessment.','Structured care'],
['outpatient-support','Outpatient Support','Scheduled recovery support for people whose assessed circumstances are appropriate for care while living at home.','Flexible support'],
['relapse-prevention','Relapse Prevention','Build practical awareness of triggers, warning signs, coping strategies, routines and support networks.','Ongoing recovery'],
['family-program','Family Program','Education and support for families and caregivers, with confidentiality and client consent at the centre.','Families & caregivers'],
['life-skills-reintegration','Life Skills & Reintegration','Practical preparation for routines, relationships, learning, work, community participation and longer-term stability.','Moving forward'],
['mental-health-wellbeing','Mental Health & Wellbeing Support','Support for emotional wellbeing within the Centre’s verified scope, with referral where additional professional care is needed.','Wellbeing'],
['aftercare','Aftercare','Continuation of recovery through planning, follow-up, check-ins, support and appropriate community connections.','Continuity of care']
];
export default function Programs(){return <><PageHero eyebrow="Programs & Care Pathways" title="Understand your options. Know what happens next." description="You do not need to choose a clinical level of care yourself. Explore our care pathways, then speak with the team so your needs and circumstances can be appropriately assessed."/>
<section className="section"><div className="container-page"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{programs.map(([slug,title,summary,context])=><Link key={slug} href={`/programs/${slug}`} className="card group block focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-900" aria-label={`Learn more about ${title}`}><p className="text-sm font-semibold text-slate-500">{context}</p><h2 className="mt-2 text-xl font-bold text-slate-950">{title}</h2><p className="mt-3 leading-7 text-slate-600">{summary}</p><span className="mt-5 inline-block font-semibold text-slate-900 group-hover:underline">Learn More →</span></Link>)}</div>
<div className="card mt-10 text-center"><h2 className="text-2xl font-bold text-slate-950">Not sure where to start?</h2><p className="mx-auto mt-3 max-w-2xl leading-7 text-slate-600">You don't need to know which program is right before asking for help. Our team can help you understand the next appropriate step.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Link className="btn-primary" href="/programs/assessment-admissions">Request a Confidential Assessment</Link><Link className="btn-secondary" href="/contact">Speak to Admissions</Link><Link className="btn-secondary" href="/grace">Ask Grace</Link></div></div>
<p className="mt-8 text-sm leading-6 text-slate-500">Program suitability and level of care are determined through appropriate professional assessment and individual circumstances, not website self-selection. Program details describe care pathways and do not constitute diagnosis, medical advice or a guarantee of outcomes.</p></div></section></>}