'use client';
import {useState} from 'react';
export default function AutomationPolicyForms({definitions,slas}){const [msg,setMsg]=useState('');async function submit(e,action){e.preventDefault();const f=new FormData(e.currentTarget);const body={action};for(const [k,v] of f.entries())body[k]=v;const r=await fetch('/api/graceflow/designer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();setMsg(r.ok?'Saved. Refresh to see the new policy.':d.error||'Could not save.');if(r.ok)e.currentTarget.reset()}const defs=definitions||[];return <div className="grid gap-5 xl:grid-cols-2">
 <Policy title="Event trigger" help="Start a published workflow when a named GraceFlow event occurs."><form onSubmit={e=>submit(e,'add_trigger')} className="grid gap-3"><Def defs={defs}/><input name="eventName" required placeholder="e.g. admission.submitted" className="input"/><input name="sourceModule" placeholder="Source module (optional)" className="input"/><button className="btn">Add trigger</button></form></Policy>
 <Policy title="Scheduled workflow" help="Run recurring workflows using Africa/Nairobi time."><form onSubmit={e=>submit(e,'add_schedule')} className="grid gap-3"><Def defs={defs}/><input name="name" required placeholder="Schedule name" className="input"/><select name="cadence" className="input"><option>daily</option><option>hourly</option><option>weekly</option><option>monthly</option><option>once</option></select><input name="hourOfDay" type="number" min="0" max="23" defaultValue="8" className="input"/><button className="btn">Add schedule</button></form></Policy>
 <Policy title="Approval matrix rule" help="Define role-based approval requirements, including amount bands."><form onSubmit={e=>submit(e,'add_approval_rule')} className="grid gap-3"><Def defs={defs}/><input name="actionKey" required placeholder="Action key" className="input"/><select name="approverRole" className="input"><option>manager</option><option>administrator</option><option>finance</option><option>accountant</option><option>clinician</option><option>hr</option><option>procurement</option></select><div className="grid grid-cols-2 gap-2"><input name="amountMin" type="number" placeholder="Min KES" className="input"/><input name="amountMax" type="number" placeholder="Max KES" className="input"/></div><input name="minApprovals" type="number" min="1" defaultValue="1" className="input"/><button className="btn">Add approval rule</button></form></Policy>
 <Policy title="SLA + escalation" help="Set a service target and escalate breaches to an accountable role."><form onSubmit={e=>submit(e,'add_sla')} className="grid gap-3"><Def defs={defs}/><input name="name" required placeholder="SLA name" className="input"/><input name="taskType" placeholder="Task type (optional)" className="input"/><div className="grid grid-cols-2 gap-2"><input name="targetMinutes" type="number" defaultValue="240" className="input"/><input name="warningMinutes" type="number" defaultValue="60" className="input"/></div><button className="btn">Add SLA</button></form><div className="my-4 border-t"/><form onSubmit={e=>submit(e,'add_escalation')} className="grid gap-3"><select name="slaPolicyId" className="input"><option value="">Any SLA</option>{(slas||[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="name" required placeholder="Escalation name" className="input"/><select name="threshold" className="input"><option>breach</option><option>warning</option><option>overdue</option></select><select name="targetRole" className="input"><option>manager</option><option>administrator</option><option>super_admin</option><option>helpdesk</option><option>finance</option><option>clinician</option></select><button className="btn">Add escalation</button></form></Policy>
 {msg&&<div className="xl:col-span-2 rounded-xl border bg-white px-4 py-3 text-sm">{msg}</div>}
 </div>}
function Policy({title,help,children}){return <section className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="font-black">{title}</h3><p className="mt-1 mb-4 text-sm leading-6 text-slate-500">{help}</p>{children}</section>}
function Def({defs}){return <select name="definitionId" required className="input"><option value="">Select workflow</option>{defs.map(d=><option key={d.id} value={d.id}>{d.name} · {d.module}</option>)}</select>}
