'use client';

import {useEffect,useRef,useState} from 'react';
import {SparklesIcon,XMarkIcon,PaperAirplaneIcon,StopIcon,ChevronDownIcon,InformationCircleIcon} from '@heroicons/react/24/outline';
import GraceResponseActions from './GraceResponseActions';

const WELCOME="Hi 👋 I’m Grace. I’m here to help you understand the Centre, explore your options, find recovery resources, or take the next step when you’re ready.\n\nWhat would you like help with today?";
const START_ACTIONS=['Understand my options','Help for someone I care about','Book a confidential assessment','Ask a question'];

export default function GraceChatPanel({open,onClose,authenticated=false,context='my_space'}){
 const [messages,setMessages]=useState([{id:'welcome',role:'grace',text:WELCOME,sources:[],quickActions:START_ACTIONS}]);
 const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const [learn,setLearn]=useState(false); const [nearBottom,setNearBottom]=useState(true);
 const abortRef=useRef(null),scrollRef=useRef(null),bottomRef=useRef(null);
 useEffect(()=>{if(nearBottom)bottomRef.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages,loading,nearBottom]);
 function onScroll(){const e=scrollRef.current;if(!e)return;setNearBottom(e.scrollHeight-e.scrollTop-e.clientHeight<120)}
 async function ask(text,{regenerate=false}={}){if(!text||loading)return;if(!regenerate)setMessages(m=>[...m,{id:`u-${Date.now()}`,role:'user',text}]);setLoading(true);const c=new AbortController();abortRef.current=c;try{const r=await fetch('/api/grace/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,context}),signal:c.signal});const d=await r.json();setMessages(m=>[...m,{id:`g-${Date.now()}`,role:'grace',text:d.answer||d.error||'I could not answer that just now.',sources:d.sources||[],quickActions:d.quickActions||[],prompt:text,alternative:regenerate,boundary:d.boundary}])}catch(e){if(e?.name!=='AbortError')setMessages(m=>[...m,{id:`g-${Date.now()}`,role:'grace',text:'I could not connect just now. You can still contact the Centre directly if you need assistance.',sources:[],prompt:text}])}finally{setLoading(false);abortRef.current=null}}
 function send(e){e?.preventDefault();const t=input.trim();if(!t||loading)return;setInput('');ask(t)}
 if(!open)return null;
 return <div className="fixed inset-0 z-[80] bg-slate-950/25 backdrop-blur-sm sm:flex sm:items-end sm:justify-end sm:p-5"><section className="flex h-full w-full flex-col overflow-hidden bg-white shadow-2xl sm:h-[720px] sm:max-h-[88vh] sm:w-[520px] sm:rounded-[30px]">
  <header className="shrink-0 border-b border-slate-100 p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-violet-100 text-violet-700"><SparklesIcon className="h-6 w-6"/></div><div><h2 className="font-black text-slate-950">Grace</h2><button onClick={()=>setLearn(v=>!v)} aria-expanded={learn} className="mt-0.5 inline-flex items-center gap-1 text-left text-xs text-slate-500 hover:text-violet-700"><InformationCircleIcon className="h-3.5 w-3.5"/>AI support and care-navigation assistant · Learn more</button></div></div><button aria-label="Close Grace" onClick={onClose} className="rounded-xl p-2 hover:bg-slate-100 focus:outline-none focus:ring-2 focus:ring-violet-400"><XMarkIcon className="h-5 w-5"/></button></div>{learn&&<div className="mt-3 rounded-2xl bg-slate-50 p-3 text-xs leading-5 text-slate-600"><b>Grace can</b> explain Centre services, share approved recovery education, support reflections, navigate the site and help arrange appointments or callbacks. <b>Grace does not</b> diagnose, prescribe, replace professional assessment or provide emergency services.</div>}</header>
  <div ref={scrollRef} onScroll={onScroll} className="relative flex-1 space-y-5 overflow-y-auto overflow-x-hidden px-4 py-5 pb-28 sm:px-5" aria-live="polite" aria-label="Grace conversation">{messages.map(m=><div key={m.id} className={m.role==='user'?'ml-auto max-w-[88%]':'max-w-[92%] sm:max-w-[680px]'}><div className={m.role==='user'?'whitespace-pre-line rounded-3xl rounded-br-lg bg-violet-600 px-4 py-3 text-[15px] leading-6 text-white':'whitespace-pre-line rounded-3xl rounded-bl-lg border border-slate-100 bg-slate-50 px-4 py-3 text-[15px] leading-6 text-slate-800'}>{m.text}</div>{m.role==='grace'&&<><GraceResponseActions text={m.text} sources={m.sources||[]} context={context} authenticated={authenticated} canRegenerate={Boolean(m.prompt)} onRegenerate={m.prompt?()=>ask(m.prompt,{regenerate:true}):null}/>{m.quickActions?.length>0&&<div className="mt-2 flex flex-wrap gap-2">{m.quickActions.slice(0,4).map(a=><button key={a} onClick={()=>a.toLowerCase().includes('book a confidential assessment')?window.location.assign('/book-assessment'):ask(a)} className="min-h-11 rounded-full border border-violet-200 bg-white px-3 py-2 text-xs font-semibold text-violet-800 hover:bg-violet-50 focus:outline-none focus:ring-2 focus:ring-violet-400">{a}</button>)}</div>}</>}</div>)}{loading&&<div className="max-w-[92%]"><div className="rounded-3xl rounded-bl-lg bg-slate-50 px-4 py-3 text-sm text-slate-500">Grace is checking the most useful next step…</div><button onClick={()=>abortRef.current?.abort()} className="mt-2 inline-flex min-h-11 items-center gap-2 rounded-xl px-3 text-xs font-semibold text-slate-600 hover:bg-slate-100"><StopIcon className="h-4 w-4"/>Stop generating</button></div>}<div ref={bottomRef}/></div>
  {!nearBottom&&<button onClick={()=>{setNearBottom(true);bottomRef.current?.scrollIntoView({behavior:'smooth'})}} className="absolute bottom-24 right-6 z-10 inline-flex min-h-11 items-center gap-1 rounded-full border border-slate-200 bg-white px-3 text-xs font-bold text-slate-700 shadow-lg"><ChevronDownIcon className="h-4 w-4"/>Jump to latest</button>}
  <div className="shrink-0 border-t border-slate-100 bg-white p-4 pb-[calc(1rem+env(safe-area-inset-bottom))]"><form onSubmit={send} className="flex gap-2"><label className="sr-only" htmlFor="grace-message">Message Grace</label><input id="grace-message" value={input} onChange={e=>setInput(e.target.value)} className="min-w-0 flex-1 rounded-2xl border border-slate-200 px-4 py-3 text-base outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100" placeholder="Message Grace…"/><button aria-label="Send message" disabled={loading} className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-violet-600 text-white hover:bg-violet-700 focus:outline-none focus:ring-2 focus:ring-violet-400 disabled:opacity-50"><PaperAirplaneIcon className="h-5 w-5"/></button></form></div>
 </section></div>
}
