import Link from 'next/link';
import {requireSession} from '@/lib/auth';
import AppShell from '@/components/app/AppShell';
import DataError from '@/components/app/DataError';
import {staffNav} from '@/lib/nav';
import {designerIndex} from '@/lib/graceflow-control';
import CreateWorkflowForm from '@/components/graceflow/CreateWorkflowForm';
import StatusBadge from '@/components/app/StatusBadge';

const roles=['administrator','manager','super_admin'];
export default async function Page(){const s=await requireSession(roles);let d,error;try{d=await designerIndex(s.token)}catch(e){error=e.message}return <AppShell title="Workflow Designer" subtitle="Design, version, test and publish executable GraceFlow processes" role="GraceFlow design" nav={staffNav}>{error?<DataError message={error}/>:<><section className="rounded-[2rem] bg-slate-950 p-7 text-white"><div className="max-w-3xl"><div className="text-xs font-black uppercase tracking-[.2em] text-grace-300">Design safely</div><h2 className="mt-3 text-3xl font-black">Draft first. Publish intentionally.</h2><p className="mt-3 text-sm leading-7 text-slate-300">Workflow definitions are versioned. Draft changes never alter the currently published automation until an authorised staff member publishes a version.</p></div></section><div className="mt-6 flex items-center justify-between"><div><h2 className="text-xl font-black">Workflow library</h2><p className="mt-1 text-sm text-slate-500">Care and enterprise automations in one governed catalogue.</p></div><CreateWorkflowForm/></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{d.defs.map(x=>{const versions=d.versions.filter(v=>v.workflow_definition_id===x.id);const pub=versions.find(v=>v.status==='published');const draft=versions.find(v=>v.status==='draft');const triggers=d.triggers.filter(t=>t.workflow_definition_id===x.id).length;const schedules=d.schedules.filter(t=>t.workflow_definition_id===x.id&&t.enabled).length;return <Link key={x.id} href={`/staff/graceflow/designer/${x.id}`} className="rounded-3xl border border-slate-200 bg-white p-5 hover:border-grace-300 hover:shadow-lg"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[.14em] text-grace-700">{x.module}</div><h3 className="mt-1 text-lg font-black">{x.name}</h3></div><StatusBadge tone={x.status==='active'?'good':'neutral'}>{x.status}</StatusBadge></div><p className="mt-2 text-sm leading-6 text-slate-500">{x.description||'No description yet.'}</p><div className="mt-4 grid grid-cols-4 gap-2 text-center"><Mini l="Published" v={pub?`v${pub.version}`:'—'}/><Mini l="Draft" v={draft?`v${draft.version}`:'—'}/><Mini l="Triggers" v={triggers}/><Mini l="Schedules" v={schedules}/></div></Link>})}</div></>}</AppShell>}
function Mini({l,v}){return <div className="rounded-xl bg-slate-50 p-2"><div className="font-black">{v}</div><div className="text-[10px] text-slate-500">{l}</div></div>}
