import {requireSession} from '@/lib/auth';
import AppShell from '@/components/app/AppShell';
import {staffNav} from '@/lib/nav';
import {dbSelect} from '@/lib/supabase-rest';
import AutomationPolicyForms from '@/components/graceflow/AutomationPolicyForms';
import {dateTime} from '@/lib/format';

export default async function Page(){const s=await requireSession(['administrator','manager','super_admin']);const [defs,triggers,schedules,approvals,slas,escalations]=await Promise.all([dbSelect('workflow_definitions','select=id,name,module,workflow_key,status&order=module,name',s.token),dbSelect('workflow_triggers','select=*&order=created_at.desc',s.token),dbSelect('workflow_schedules','select=*&order=next_run_at.asc',s.token),dbSelect('workflow_approval_matrix_rules','select=*&order=priority',s.token),dbSelect('workflow_sla_policies','select=*&order=created_at.desc',s.token),dbSelect('workflow_escalation_rules','select=*&order=created_at.desc',s.token)]);return <AppShell title="Automation & Policy Centre" subtitle="Triggers, schedules, approval matrices, service levels and escalation rules" role="GraceFlow control" nav={staffNav}><section className="rounded-[2rem] bg-slate-950 p-7 text-white"><h2 className="text-3xl font-black">Rules that operate after the page closes.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-300">GraceFlow evaluates event triggers, scheduled work, SLA deadlines and escalation policies independently of a staff member keeping a dashboard open. Configure rules here; run the engine tick from a secure scheduler in production.</p></section><div className="mt-6"><AutomationPolicyForms definitions={defs||[]} slas={slas||[]}/></div><div className="mt-7 grid gap-5 xl:grid-cols-2"><List title="Active triggers" rows={(triggers||[]).map(x=>`${x.event_name||x.trigger_type} · ${x.source_module||'any module'}`)}/><List title="Schedules" rows={(schedules||[]).map(x=>`${x.name} · ${x.cadence} · next ${dateTime(x.next_run_at)}`)}/><List title="Approval matrix" rows={(approvals||[]).map(x=>`${x.action_key} → ${x.approver_role||'named approver'} · ${x.min_approvals} approval(s)`)}/><List title="SLA & escalation" rows={[...(slas||[]).map(x=>`${x.name} · target ${x.target_minutes} min`),...(escalations||[]).map(x=>`${x.name} · ${x.threshold} → ${x.target_role||x.action_type}`)]}/></div></AppShell>}
function List({title,rows}){return <section className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="font-black">{title}</h3><div className="mt-3 grid gap-2">{rows.length?rows.map((x,i)=><div key={i} className="rounded-xl bg-slate-50 px-3 py-2 text-sm text-slate-600">{x}</div>):<p className="text-sm text-slate-400">Nothing configured yet.</p>}</div></section>}
